!!python/object/new:utils.setting.DotDict
dictitems:
  exp_name: cmi
  description: ''
  save_dir: runs/train/cmi/2024_11_14_16_40_04_56
  wandb_pj_name: cmi
  wandb_entity: chrenx
  disable_wandb: true
  seed: 42
  debug: false
  model_n: 1
  data_dir: data/processed_data
  apply_gausion_noise: true
  gauss_mean: 0.0
  gauss_std: 0.01
  cuda_id: '9'
  penalty_cost: 0
  batch_size: 64
  lr: 0.001
  cur_time: '2024_11_14_16_40_04_56'
  weights_dir: runs/train/cmi/2024_11_14_16_40_04_56/weights
  codes_dir: runs/train/cmi/2024_11_14_16_40_04_56/codes
  device_info: NVIDIA L40S
  device: cuda:9
